name: New sponsor profile
description: This template is used to collect necessary data for creating sponsor profiles on the website.
title: "[SPONSOR]: "
labels: ["profile", "sponsor"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in sponsoring.
        Please fill out the following information to create your sponsor profile.

  - type: input
    id: name
    attributes:
      label: Organization or Company Name
      description: The full name of your organization.
      placeholder: e.g., "AwesomeCorp"
    validations:
      required: true

  - type: input
    id: headline
    attributes:
      label: Tagline
      description: A short description of your organization (max 80 characters).
      placeholder: e.g., "Making the world a better place"


  - type: textarea
    id: content
    attributes:
      label: About
      description: A longer description about your organization (2-4 paragraphs).
      placeholder: |
        Tell us about your organization.

        What is your mission and values? Why do you want to sponsor?
    validations:
      required: false

  - type: input
    id: website
    attributes:
      label: Website
      description: URL to your company website.
      placeholder: "https://www.example.com"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: Your contact email.
      placeholder: "contact@example.com"

  - type: input
    id: cell
    attributes:
      label: Phone
      description: Your contact phone number.
      placeholder: "+45 12 34 56 78"

  - type: input
    id: x
    attributes:
      label: X (formerly Twitter)
      description: Your X handle (without the @).
      placeholder: "awesomecorp"

  - type: input
    id: linkedin
    attributes:
      label: LinkedIn
      description: Your LinkedIn profile name.
      placeholder: "awesomecorp"

  - type: input
    id: github
    attributes:
      label: GitHub
      description: Your GitHub username.
      placeholder: "awesomecorp"

  - type: textarea
    id: image
    attributes:
      label: Logo
      description: |
        Upload or attach your company logo.
        The image should be in high resolution (PNG, SVG, or JPG format).
        Ideally in a square format (at least 400x400 pixels).

        You can attach the file by dragging it into this text field.
      placeholder: Drag and drop your logo file here.
    validations:
      required: true

